
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.4
jobs:
  build:
    docker:
      - image: cimg/node:20.0.0-browsers
    working_directory: ~/script-runner
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn build

workflows:
  jobs:
    - build