version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.4
jobs:
  build:
    docker:
      - image: cimg/node:20.0.0-browsers
    working_directory: ~/script-runner
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-deps-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build Project
          command: NODE_OPTIONS="--max-old-space-size=4096" yarn build
      - persist_to_workspace:
            root: .
            paths:
              - build  # Adjust this to your build directory (e.g., 'dist' or 'out')
 
  test:
    docker:
      - image: cimg/node:20.0.0-browsers
    working_directory: ~/script-runner
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - run: ls -la
workflows:
  version: 2
  main_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
