version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.4
jobs:
  test:
    docker:
      - image: cimg/node:20.0.0-browsers
    working_directory: ~/script-runner
    steps:
      - browser-tools/install-browser-tools:
          install-firefox: false
          install-chrome: true
          install-chromedriver: false
          install-geckodriver: false
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-deps-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build Project
          command: NODE_OPTIONS="--max-old-space-size=4096" yarn build
      - run:
          name: test
          command: |
           cd test
           yarn install
           yarn test

workflows:
  version: 2
  main_workflow:
    jobs:
      - test
